sudo: false

dist: xenial

language: php

branches:
  only:
    - master
    - /^\d+\.\d+$/

php:
    - 7.1.26

env:
  - COMPOSER=travis.json

cache:
  directories:
    - $HOME/.composer

before_script:
  - /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048
  - /sbin/mkswap /var/swap.1
  - /sbin/swapon /var/swap.1
  
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - cp dev.json travis.json # avoid dev.lock file and composer.json with a stable version
  - travis_retry travis_wait composer install --prefer-dist --optimize-autoloader --no-interaction  --no-suggest
  - set +e; DIFF=$(git diff --name-only --diff-filter=ACMR $TRAVIS_COMMIT_RANGE | grep -e ".*\.php$"); set -e;

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs ./src -p --encoding=utf-8 --extensions=php --standard=PSR2
  - ./vendor/bin/php-cs-fixer fix --dry-run --config=./vendor/oro/platform/build/.php_cs --path-mode=intersection ./src
  - if [[ $DIFF ]]; then ./vendor/bin/phpmd ${DIFF//$'\n'/,} text ./vendor/oro/platform/build/phpmd.xml --suffixes php; fi
